### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eharik** [pdalpra/jooq-codegen-sbt#4]
Pierre:  Lukas Eder recommended your plugin for scala/sbt integration.  Can you update the README with use instructions, please?  It would be much appreciated.

**Comment by pdalpra** [comment]
Sure, and I'll finally take the time to publish the plugin to Bintray too :)

**Comment by eharik** [comment]
Awesome, looking forward to it.

**Comment by ktham** [comment]
also looking forward to it :-)

**Comment by jvliwanag** [comment]
Hi @pdalpra, got to publishing it yet? :)

**Comment by pdalpra** [comment]
Hasn't really worked on it for a long time, but I'll give it some love ;)

**Comment by pdalpra** [comment]
@jvliwanag @eharik @ktham It took we a while, but I'll do some cleanup + release and document the plugin in the coming days.

**Comment by pdalpra** [comment]
Documentation has been published, release is on its way !
